import { SearchMoverListResponse, SearchMoverDetailResponse, MovingType, Region } from '@/shared/types/types';

// 기사님 목록 조회 목 데이터 (20개)
export const mockMoverListResponse: SearchMoverListResponse = {
  list: [
    {
      id: '1',
      idNum: 1,
      nickName: '김코드',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 136,
      totalRating: 5.0,
      reviewCounts: 178,
      intro: '고객님의 물품을 안전하게 운송해 드립니다.',
      career: 7,
      confirmedCounts: 334,
    },
    {
      id: '2',
      idNum: 2,
      nickName: '박안전',
      profileImage: null,
      serviceList: ['FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: true,
      isLiked: true,
      likeCount: 89,
      totalRating: 4.8,
      reviewCounts: 142,
      intro: '신속하고 정확한 이사 서비스를 제공합니다.',
      career: 5,
      confirmedCounts: 267,
    },
    {
      id: '3',
      idNum: 3,
      nickName: '이신속',
      profileImage: null,
      serviceList: ['SMALL_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 203,
      totalRating: 4.9,
      reviewCounts: 256,
      intro: '소형 이사 전문으로 빠르고 깔끔하게 처리합니다.',
      career: 8,
      confirmedCounts: 445,
    },
    {
      id: '4',
      idNum: 4,
      nickName: '최프로',
      profileImage: null,
      serviceList: ['OFFICE_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 167,
      totalRating: 4.7,
      reviewCounts: 198,
      intro: '사무실 이전 전문가입니다.',
      career: 10,
      confirmedCounts: 389,
    },
    {
      id: '5',
      idNum: 5,
      nickName: '정친절',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 124,
      totalRating: 4.6,
      reviewCounts: 167,
      intro: '모든 종류의 이사를 친절하게 도와드립니다.',
      career: 6,
      confirmedCounts: 298,
    },
    {
      id: '6',
      idNum: 6,
      nickName: '강믿음',
      profileImage: null,
      serviceList: ['FAMILY_MOVE'],
      isAssigned: true,
      isLiked: false,
      likeCount: 95,
      totalRating: 4.8,
      reviewCounts: 134,
      intro: '가족 이사를 안전하게 책임집니다.',
      career: 4,
      confirmedCounts: 223,
    },
    {
      id: '7',
      idNum: 7,
      nickName: '윤깔끔',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 178,
      totalRating: 4.9,
      reviewCounts: 201,
      intro: '깔끔하고 정돈된 이사 서비스를 제공합니다.',
      career: 9,
      confirmedCounts: 356,
    },
    {
      id: '8',
      idNum: 8,
      nickName: '장경험',
      profileImage: null,
      serviceList: ['OFFICE_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 145,
      totalRating: 4.5,
      reviewCounts: 189,
      intro: '15년 경력의 베테랑 기사입니다.',
      career: 15,
      confirmedCounts: 567,
    },
    {
      id: '9',
      idNum: 9,
      nickName: '임빠름',
      profileImage: null,
      serviceList: ['SMALL_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 112,
      totalRating: 4.7,
      reviewCounts: 156,
      intro: '빠른 소형 이사 전문가입니다.',
      career: 3,
      confirmedCounts: 189,
    },
    {
      id: '10',
      idNum: 10,
      nickName: '한정성',
      profileImage: null,
      serviceList: ['FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: true,
      isLiked: false,
      likeCount: 156,
      totalRating: 4.8,
      reviewCounts: 178,
      intro: '정성스럽고 꼼꼼한 이사 서비스를 약속드립니다.',
      career: 7,
      confirmedCounts: 312,
    },
    {
      id: '11',
      idNum: 11,
      nickName: '오세심',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 134,
      totalRating: 4.6,
      reviewCounts: 145,
      intro: '세심한 포장과 운송으로 안전하게 이사해드립니다.',
      career: 5,
      confirmedCounts: 234,
    },
    {
      id: '12',
      idNum: 12,
      nickName: '서전문',
      profileImage: null,
      serviceList: ['OFFICE_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 89,
      totalRating: 4.9,
      reviewCounts: 123,
      intro: '사무용품 이전 전문가로 안전하게 처리합니다.',
      career: 8,
      confirmedCounts: 278,
    },
    {
      id: '13',
      idNum: 13,
      nickName: '남친화',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 198,
      totalRating: 4.7,
      reviewCounts: 234,
      intro: '친화적이고 상냥한 서비스로 모시겠습니다.',
      career: 6,
      confirmedCounts: 345,
    },
    {
      id: '14',
      idNum: 14,
      nickName: '조꼼꼼',
      profileImage: null,
      serviceList: ['FAMILY_MOVE'],
      isAssigned: true,
      isLiked: false,
      likeCount: 167,
      totalRating: 4.8,
      reviewCounts: 189,
      intro: '꼼꼼한 포장과 안전한 운송을 보장합니다.',
      career: 9,
      confirmedCounts: 398,
    },
    {
      id: '15',
      idNum: 15,
      nickName: '배신뢰',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'OFFICE_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 145,
      totalRating: 4.6,
      reviewCounts: 167,
      intro: '신뢰할 수 있는 이사 파트너가 되겠습니다.',
      career: 4,
      confirmedCounts: 256,
    },
    {
      id: '16',
      idNum: 16,
      nickName: '문안심',
      profileImage: null,
      serviceList: ['FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 123,
      totalRating: 4.9,
      reviewCounts: 145,
      intro: '안심하고 맡길 수 있는 이사 서비스를 제공합니다.',
      career: 11,
      confirmedCounts: 456,
    },
    {
      id: '17',
      idNum: 17,
      nickName: '유만족',
      profileImage: null,
      serviceList: ['SMALL_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 178,
      totalRating: 4.7,
      reviewCounts: 198,
      intro: '고객 만족을 최우선으로 하는 기사입니다.',
      career: 7,
      confirmedCounts: 334,
    },
    {
      id: '18',
      idNum: 18,
      nickName: '홍정직',
      profileImage: null,
      serviceList: ['FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: true,
      isLiked: false,
      likeCount: 156,
      totalRating: 4.8,
      reviewCounts: 178,
      intro: '정직하고 성실한 이사 서비스를 약속드립니다.',
      career: 8,
      confirmedCounts: 367,
    },
    {
      id: '19',
      idNum: 19,
      nickName: '김완벽',
      profileImage: null,
      serviceList: ['SMALL_MOVE', 'FAMILY_MOVE', 'OFFICE_MOVE'],
      isAssigned: false,
      isLiked: true,
      likeCount: 234,
      totalRating: 5.0,
      reviewCounts: 267,
      intro: '완벽한 이사를 위해 최선을 다하겠습니다.',
      career: 12,
      confirmedCounts: 489,
    },
    {
      id: '20',
      idNum: 20,
      nickName: '박베테랑',
      profileImage: null,
      serviceList: ['OFFICE_MOVE'],
      isAssigned: false,
      isLiked: false,
      likeCount: 189,
      totalRating: 4.9,
      reviewCounts: 223,
      intro: '20년 경력의 베테랑으로 안전한 이사를 보장합니다.',
      career: 20,
      confirmedCounts: 678,
    },
  ],
  orderNextCursor: 21,
  idNumNextCursor: 21,
  hasNext: false,
};

// 기사님 상세 조회 목 데이터 (첫 번째 기사님 기준)
export const mockMoverDetailResponse: SearchMoverDetailResponse = {
  id: '1',
  idNum: 1,
  nickName: '김코드',
  profileImage: null,
  serviceList: ['SMALL_MOVE', 'FAMILY_MOVE'],
  isAssigned: false,
  isLiked: false,
  likeCount: 136,
  totalRating: 5.0,
  reviewCounts: 178,
  intro: '고객님의 물품을 안전하게 운송해 드립니다.',
  career: 7,
  confirmedCounts: 334,
  detailDescription: `안녕하세요! 7년 경력의 김코드 기사입니다.

고객님의 소중한 물품을 마치 제 것처럼 소중히 다루며, 안전하고 신속한 이사 서비스를 제공해드리고 있습니다.

【전문 분야】
✓ 소형 이사 (원룸, 투룸)
✓ 가정 이사 (빌라, 아파트)
✓ 포장 및 정리 서비스

【서비스 특징】
• 꼼꼼한 포장으로 파손 방지
• 정시 도착 및 신속한 작업
• 친절하고 정중한 서비스
• 합리적인 가격 책정

【고객 후기】
"정말 친절하시고 물건도 하나도 안 깨뜨리고 옮겨주셨어요!"
"시간 약속도 잘 지키시고 가격도 합리적이에요."
"다음에도 꼭 김코드 기사님께 부탁드리고 싶어요!"

언제든지 편하게 연락주세요. 최선을 다해 도와드리겠습니다!`,
  serviceArea: ['SEOUL', 'GYEONGGI', 'INCHEON'],
};

// 찜한 기사님 목록 (isLiked: true인 기사님 3명)
export const likeMoverList = mockMoverListResponse.list.filter((mover) => mover.isLiked === true).slice(0, 3);
