import { UserCardData } from '@/shared/components/Card/CardPresets';

export const mockData: UserCardData[] = [
  {
    id: '1',
    name: '김인서',
    userProfileImage: '/assets/images/sample/user1.jpg',
    customerId: '1',
    moveDay: '2025-07-31',
    startPoint: '서울시 강남구',
    endPoint: '경기도 성남시',
    quoteAmount: 180000,
    comment: '이사 당일 오전 9시에 도착 부탁드립니다.',
    likeCount: 12,
    service: ['소형이사', '사무실이사'],
    provideService: ['가정이사', '짐보관'],
    region: ['서울', '경기'],
    career: 5,
    confirmation: 30,
    detailDescription: '친절하고 꼼꼼한 기사입니다. 만족스러운 이사를 약속드려요.',
    review: {
      content: '정말 친절하시고 시간도 잘 맞춰주셨어요!',
      reviewer: 15,
      averageScore: 4.8,
    },
    createTime: '2024-07-01T12:00:00Z',
  },
  {
    id: '2',
    name: '박지은',
    userProfileImage: '/assets/images/sample/user2.jpg',
    moveDay: '2025-05-31',
    startPoint: '인천시 부평구',
    endPoint: '서울시 관악구',
    quoteAmount: 230000,
    comment: '',
    likeCount: 5,
    service: ['가정이사'],
    provideService: ['소형이사', '사무실이사'],
    region: ['인천', '서울'],
    career: 3,
    confirmation: 12,
    detailDescription: '항상 고객의 입장에서 생각하는 이삿짐 전문가입니다.',
    review: {
      content: '깔끔하게 잘 정리해주셔서 감사합니다.',
      reviewer: 7,
      averageScore: 4.5,
    },
    createTime: '2024-07-05T09:30:00Z',
  },
  {
    id: '3',
    name: '한지은',
    userProfileImage: '/assets/images/sample/user2.jpg',
    moveDay: '2025-06-01',
    startPoint: '인천시 부평구',
    endPoint: '서울시 관악구',
    quoteAmount: 230000,
    comment: '',
    likeCount: 5,
    service: ['가정이사'],
    provideService: ['소형이사', '사무실이사'],
    region: ['인천', '서울'],
    career: 3,
    confirmation: 12,
    detailDescription: '항상 고객의 입장에서 생각하는 이삿짐 전문가입니다.',
    review: {
      content: '깔끔하게 잘 정리해주셔서 감사합니다.',
      reviewer: 7,
      averageScore: 4.5,
    },
    createTime: '2024-07-05T09:30:00Z',
  },
  {
    id: '4',
    name: '정은지',
    userProfileImage: '/assets/images/sample/user2.jpg',
    moveDay: '2025-08-01',
    startPoint: '인천시 부평구',
    endPoint: '서울시 관악구',
    quoteAmount: 230000,
    comment: '',
    likeCount: 5,
    service: ['가정이사'],
    provideService: ['소형이사', '사무실이사'],
    region: ['인천', '서울'],
    career: 3,
    confirmation: 12,
    detailDescription: '항상 고객의 입장에서 생각하는 이삿짐 전문가입니다.',
    review: {
      content: '깔끔하게 잘 정리해주셔서 감사합니다.',
      reviewer: 7,
      averageScore: 4.5,
    },
    createTime: '2024-07-05T09:30:00Z',
  },
];
