import { CustomerWriteReviewListResponseData, CustomerFinishedReviewListResponseData } from '@/shared/types/types';

// 작성가능한 리뷰 목록
export const mockWriteListResponse: CustomerWriteReviewListResponseData = {
  list: [
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '김코드',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-01-15',
      startAddress: '서울특별시 강남구 역삼동 123-45',
      endAddress: '서울특별시 서초구 반포동 678-90',
      moveType: 'SMALL_MOVE',
      price: '150000',
      isAssignedMover: false,
      offerId: 'offer_001',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '박안전',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-01-20',
      startAddress: '서울특별시 송파구 잠실동 234-56',
      endAddress: '경기도 성남시 분당구 정자동 789-01',
      moveType: 'FAMILY_MOVE',
      price: '450000',
      isAssignedMover: true,
      offerId: 'offer_002',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '이신속',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-01-25',
      startAddress: '경기도 고양시 일산동구 장항동 345-67',
      endAddress: '서울특별시 마포구 상암동 890-12',
      moveType: 'SMALL_MOVE',
      price: '180000',
      isAssignedMover: false,
      offerId: 'offer_003',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '최프로',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-01',
      startAddress: '서울특별시 종로구 종로1가 456-78',
      endAddress: '서울특별시 용산구 이태원동 123-34',
      moveType: 'OFFICE_MOVE',
      price: '650000',
      isAssignedMover: false,
      offerId: 'offer_004',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '정친절',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-05',
      startAddress: '인천광역시 남동구 구월동 567-89',
      endAddress: '서울특별시 강서구 화곡동 234-45',
      moveType: 'FAMILY_MOVE',
      price: '380000',
      isAssignedMover: true,
      offerId: 'offer_005',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '강믿음',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-10',
      startAddress: '서울특별시 관악구 신림동 678-90',
      endAddress: '경기도 안양시 만안구 안양동 345-56',
      moveType: 'SMALL_MOVE',
      price: '220000',
      isAssignedMover: false,
      offerId: 'offer_006',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '윤깔끔',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-15',
      startAddress: '경기도 부천시 원미구 중동 789-01',
      endAddress: '서울특별시 영등포구 여의도동 456-67',
      moveType: 'OFFICE_MOVE',
      price: '580000',
      isAssignedMover: false,
      offerId: 'offer_007',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '장경험',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-20',
      startAddress: '서울특별시 동작구 사당동 890-12',
      endAddress: '경기도 수원시 영통구 매탄동 567-78',
      moveType: 'FAMILY_MOVE',
      price: '420000',
      isAssignedMover: true,
      offerId: 'offer_008',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '임빠름',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-02-25',
      startAddress: '서울특별시 노원구 상계동 123-34',
      endAddress: '경기도 의정부시 의정부동 678-89',
      moveType: 'SMALL_MOVE',
      price: '190000',
      isAssignedMover: false,
      offerId: 'offer_009',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '한정성',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-01',
      startAddress: '서울특별시 성북구 정릉동 234-45',
      endAddress: '경기도 남양주시 다산동 789-90',
      moveType: 'FAMILY_MOVE',
      price: '390000',
      isAssignedMover: false,
      offerId: 'offer_010',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '오세심',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-05',
      startAddress: '경기도 광명시 철산동 345-56',
      endAddress: '서울특별시 구로구 구로동 890-01',
      moveType: 'SMALL_MOVE',
      price: '165000',
      isAssignedMover: true,
      offerId: 'offer_011',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '서전문',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-10',
      startAddress: '서울특별시 중구 을지로1가 456-67',
      endAddress: '서울특별시 강동구 천호동 123-12',
      moveType: 'OFFICE_MOVE',
      price: '720000',
      isAssignedMover: false,
      offerId: 'offer_012',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '남친화',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-15',
      startAddress: '서울특별시 서대문구 연희동 567-78',
      endAddress: '경기도 파주시 교하읍 567-23',
      moveType: 'FAMILY_MOVE',
      price: '480000',
      isAssignedMover: false,
      offerId: 'offer_013',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '조꼼꼼',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-20',
      startAddress: '서울특별시 은평구 불광동 678-89',
      endAddress: '경기도 고양시 덕양구 행신동 234-34',
      moveType: 'SMALL_MOVE',
      price: '210000',
      isAssignedMover: true,
      offerId: 'offer_014',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '배신뢰',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-25',
      startAddress: '인천광역시 연수구 송도동 789-90',
      endAddress: '서울특별시 강남구 삼성동 345-45',
      moveType: 'OFFICE_MOVE',
      price: '690000',
      isAssignedMover: false,
      offerId: 'offer_015',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '문안심',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-03-30',
      startAddress: '서울특별시 양천구 목동 890-01',
      endAddress: '경기도 김포시 장기동 456-56',
      moveType: 'FAMILY_MOVE',
      price: '360000',
      isAssignedMover: false,
      offerId: 'offer_016',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '유만족',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-04-05',
      startAddress: '서울특별시 도봉구 방학동 123-12',
      endAddress: '경기도 구리시 인창동 567-67',
      moveType: 'SMALL_MOVE',
      price: '175000',
      isAssignedMover: true,
      offerId: 'offer_017',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '홍정직',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-04-10',
      startAddress: '서울특별시 광진구 자양동 234-23',
      endAddress: '경기도 하남시 풍산동 678-78',
      moveType: 'FAMILY_MOVE',
      price: '410000',
      isAssignedMover: false,
      offerId: 'offer_018',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '김완벽',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-04-15',
      startAddress: '경기도 시흥시 정왕동 345-34',
      endAddress: '서울특별시 금천구 가산동 789-89',
      moveType: 'OFFICE_MOVE',
      price: '760000',
      isAssignedMover: false,
      offerId: 'offer_019',
    },
    {
      content: '',
      rating: 0,
      reviewDate: null,
      moverName: '박베테랑',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-04-20',
      startAddress: '서울특별시 강북구 미아동 456-45',
      endAddress: '경기도 양주시 회천동 890-90',
      moveType: 'FAMILY_MOVE',
      price: '440000',
      isAssignedMover: true,
      offerId: 'offer_020',
    },
  ],
  totalPages: 1,
  currentPage: 1,
  totalCount: 20,
};

// 작성한 리뷰 목록
export const mockFinishedListResponse: CustomerFinishedReviewListResponseData = {
  list: [
    {
      content: '정말 친절하시고 물건도 하나도 안 깨뜨리고 옮겨주셨어요! 시간 약속도 잘 지키시고 매우 만족합니다.',
      rating: 5,
      reviewDate: '2024-01-10',
      moverName: '김안전',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2024-01-08',
      startAddress: '서울특별시 강남구 대치동 123-45',
      endAddress: '서울특별시 서초구 잠원동 678-90',
      moveType: 'SMALL_MOVE',
      price: '180000',
      isAssignedMover: false,
    },
    {
      content:
        '가족이사였는데 정말 꼼꼼하게 포장해주시고 안전하게 옮겨주셨습니다. 기사님이 경험이 많으셔서 안심이 되었어요.',
      rating: 5,
      reviewDate: '2023-12-25',
      moverName: '이프로',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-12-23',
      startAddress: '경기도 성남시 분당구 정자동 234-56',
      endAddress: '서울특별시 송파구 잠실동 789-01',
      moveType: 'FAMILY_MOVE',
      price: '520000',
      isAssignedMover: true,
    },
    {
      content: '사무실 이전이었는데 IT장비들을 정말 조심스럽게 다뤄주셨어요. 덕분에 문제없이 이전 완료했습니다!',
      rating: 4,
      reviewDate: '2023-12-20',
      moverName: '박신속',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-12-18',
      startAddress: '서울특별시 강남구 역삼동 345-67',
      endAddress: '서울특별시 마포구 상암동 890-12',
      moveType: 'OFFICE_MOVE',
      price: '780000',
      isAssignedMover: false,
    },
    {
      content: '원룸 이사였는데 빠르고 깔끔하게 처리해주셨어요. 가격도 합리적이고 추천드려요!',
      rating: 5,
      reviewDate: '2023-12-15',
      moverName: '최빠름',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-12-13',
      startAddress: '서울특별시 관악구 신림동 456-78',
      endAddress: '경기도 안양시 동안구 평촌동 123-34',
      moveType: 'SMALL_MOVE',
      price: '150000',
      isAssignedMover: false,
    },
    {
      content: '지정 견적으로 부탁드렸는데 역시 믿고 맡길 수 있었어요. 다음에도 꼭 부탁드리고 싶습니다.',
      rating: 5,
      reviewDate: '2023-12-10',
      moverName: '정믿음',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-12-08',
      startAddress: '인천광역시 부평구 부평동 567-89',
      endAddress: '서울특별시 강서구 화곡동 234-45',
      moveType: 'FAMILY_MOVE',
      price: '450000',
      isAssignedMover: true,
    },
    {
      content: '포장도 잘해주시고 운반도 안전하게 해주셨어요. 기사님이 정말 성실하십니다.',
      rating: 4,
      reviewDate: '2023-12-05',
      moverName: '강성실',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-12-03',
      startAddress: '서울특별시 노원구 상계동 678-90',
      endAddress: '경기도 의정부시 녹양동 345-56',
      moveType: 'SMALL_MOVE',
      price: '195000',
      isAssignedMover: false,
    },
    {
      content: '회사 이전이었는데 정말 전문적으로 처리해주셨어요. 직원들도 모두 만족했습니다!',
      rating: 5,
      reviewDate: '2023-11-30',
      moverName: '윤전문',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-28',
      startAddress: '서울특별시 종로구 종로2가 789-01',
      endAddress: '서울특별시 용산구 한남동 456-67',
      moveType: 'OFFICE_MOVE',
      price: '680000',
      isAssignedMover: false,
    },
    {
      content: '시간 약속 정확히 지키시고 일처리도 깔끔하게 해주셨어요. 매우 만족합니다.',
      rating: 4,
      reviewDate: '2023-11-25',
      moverName: '장깔끔',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-23',
      startAddress: '서울특별시 동작구 사당동 890-12',
      endAddress: '경기도 수원시 영통구 영통동 567-78',
      moveType: 'FAMILY_MOVE',
      price: '380000',
      isAssignedMover: true,
    },
    {
      content: '원룸에서 투룸으로 이사했는데 물건이 많았음에도 불구하고 꼼꼼하게 옮겨주셨어요.',
      rating: 5,
      reviewDate: '2023-11-20',
      moverName: '임꼼꼼',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-18',
      startAddress: '서울특별시 성북구 정릉동 123-34',
      endAddress: '경기도 고양시 일산동구 장항동 678-89',
      moveType: 'SMALL_MOVE',
      price: '220000',
      isAssignedMover: false,
    },
    {
      content: '이사 경험이 많으신 분 같아요. 어떻게 포장하고 옮겨야 하는지 잘 아시더라구요.',
      rating: 4,
      reviewDate: '2023-11-15',
      moverName: '한베테랑',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-13',
      startAddress: '경기도 부천시 원미구 중동 234-45',
      endAddress: '서울특별시 영등포구 당산동 789-90',
      moveType: 'FAMILY_MOVE',
      price: '420000',
      isAssignedMover: false,
    },
    {
      content: '친절하시고 설명도 자세히 해주셔서 좋았어요. 다음에도 이용하고 싶습니다.',
      rating: 5,
      reviewDate: '2023-11-10',
      moverName: '오친절',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-08',
      startAddress: '서울특별시 서대문구 연희동 345-56',
      endAddress: '경기도 파주시 운정동 890-01',
      moveType: 'SMALL_MOVE',
      price: '185000',
      isAssignedMover: true,
    },
    {
      content: '사무실 이전 전문가답게 정말 체계적으로 진행해주셨어요. 업무 중단 시간도 최소화했습니다.',
      rating: 5,
      reviewDate: '2023-11-05',
      moverName: '서체계',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-11-03',
      startAddress: '서울특별시 중구 명동 456-67',
      endAddress: '서울특별시 강동구 암사동 123-12',
      moveType: 'OFFICE_MOVE',
      price: '750000',
      isAssignedMover: false,
    },
    {
      content: '가격 대비 정말 만족스러운 서비스였어요. 기사님도 정말 성격이 좋으시더라구요!',
      rating: 4,
      reviewDate: '2023-10-30',
      moverName: '남좋음',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-28',
      startAddress: '서울특별시 은평구 불광동 567-78',
      endAddress: '경기도 고양시 덕양구 행신동 234-34',
      moveType: 'FAMILY_MOVE',
      price: '460000',
      isAssignedMover: false,
    },
    {
      content: '포장재료도 충분히 가져오시고 정말 안전하게 옮겨주셨어요. 추천합니다!',
      rating: 5,
      reviewDate: '2023-10-25',
      moverName: '조안전',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-23',
      startAddress: '인천광역시 연수구 송도동 678-89',
      endAddress: '서울특별시 강남구 논현동 345-45',
      moveType: 'SMALL_MOVE',
      price: '200000',
      isAssignedMover: true,
    },
    {
      content: '신혼집 이사였는데 정말 깔끔하게 해주셨어요. 새 가구도 하나도 손상없이 옮겨주셨습니다.',
      rating: 5,
      reviewDate: '2023-10-20',
      moverName: '배신혼',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-18',
      startAddress: '서울특별시 양천구 목동 789-90',
      endAddress: '경기도 김포시 장기동 456-56',
      moveType: 'FAMILY_MOVE',
      price: '350000',
      isAssignedMover: false,
    },
    {
      content: '원룸 이사인데도 정성스럽게 해주셨어요. 기사님 덕분에 스트레스 없이 이사했습니다.',
      rating: 4,
      reviewDate: '2023-10-15',
      moverName: '문정성',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-13',
      startAddress: '서울특별시 도봉구 방학동 890-01',
      endAddress: '경기도 구리시 수택동 123-23',
      moveType: 'SMALL_MOVE',
      price: '175000',
      isAssignedMover: false,
    },
    {
      content: '회사 이전이었는데 직원분들도 친절하시고 일정대로 완료해주셨어요. 고맙습니다!',
      rating: 5,
      reviewDate: '2023-10-10',
      moverName: '유일정',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-08',
      startAddress: '서울특별시 광진구 자양동 234-34',
      endAddress: '경기도 하남시 미사동 567-67',
      moveType: 'OFFICE_MOVE',
      price: '820000',
      isAssignedMover: true,
    },
    {
      content: '이사 비용이 합리적이고 서비스도 정말 좋았어요. 다음에도 꼭 연락드리겠습니다.',
      rating: 4,
      reviewDate: '2023-10-05',
      moverName: '홍합리',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-10-03',
      startAddress: '경기도 시흥시 정왕동 345-45',
      endAddress: '서울특별시 금천구 독산동 678-78',
      moveType: 'FAMILY_MOVE',
      price: '400000',
      isAssignedMover: false,
    },
    {
      content: '20년 경력이라고 하시더니 정말 노하우가 대단하시더라구요. 완전 만족합니다!',
      rating: 5,
      reviewDate: '2023-09-30',
      moverName: '김노하우',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-09-28',
      startAddress: '서울특별시 강북구 미아동 789-89',
      endAddress: '경기도 양주시 회천동 890-90',
      moveType: 'SMALL_MOVE',
      price: '190000',
      isAssignedMover: false,
    },
    {
      content: '처음부터 끝까지 정말 만족스러웠어요. 이사 스트레스가 전혀 없었습니다. 감사합니다!',
      rating: 5,
      reviewDate: '2023-09-25',
      moverName: '박만족',
      moverProfileImage: '/assets/images/profile-icon/login-default-36x36.svg',
      moveDate: '2023-09-23',
      startAddress: '서울특별시 강서구 등촌동 123-01',
      endAddress: '경기도 광명시 철산동 456-12',
      moveType: 'FAMILY_MOVE',
      price: '480000',
      isAssignedMover: true,
    },
  ],
  totalPages: 1,
  currentPage: 1,
  totalCount: 20,
};
