import { SxProps } from '@mui/material';

interface TypoStyles {
  [key: string]: SxProps;
}

// 기본 타이포 text_{weight}_{size} 로 잡아놨어요. 혹시 작업하다가 추가로 필요한 스타일이 있으면 이름 자유롭게 추가해서 쓰셔도 됩니다.
// 혹시 빠진게 있다면 여기에 추가하고 Typo.tsx TypoClassName 에도 추가해주세요
// 만약 반응형으로 폰트 사이즈가 달라진다면 스타일에 미디어쿼리 적용할 수 있어요.
export const typographyStyles: TypoStyles = {
  text_B_40to64: {
    fontFamily: 'pretendard',
    fontSize: '64px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    '@media (max-width: 1200px)': {
      fontSize: '40px',
      lineHeight: '150%',
    },
  },
  text_B_24to38: {
    fontFamily: 'pretendard',
    fontSize: '38px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '150%',
    '@media (max-width: 1200px)': {
      fontSize: '24px',
      lineHeight: '26px',
    },
  },
  text_B_20to32: {
    fontFamily: 'pretendard',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '42px',
    '@media (max-width: 1200px)': {
      fontSize: '20px',
      lineHeight: '24px',
    },
  },
  text_B_18to24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '18px',
      lineHeight: '26px',
    },
  },
  text_B_14to20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_SB_12to14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '24px',
    '@media (max-width: 1200px)': {
      fontSize: '12px',
      lineHeight: '20px',
    },
  },
  text_R_14to16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_R_14to20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_R_16to24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '16px',
      lineHeight: '26px',
    },
  },
  text_SB_14to20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_SB_14to24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_SB_16to20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '16px',
      lineHeight: '26px',
    },
  },
  text_SB_16to24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '16px',
      lineHeight: '26px',
    },
  },
  text_M_12to16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '12px',
      lineHeight: '20px',
    },
  },
  text_M_12to14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
    '@media (max-width: 1200px)': {
      fontSize: '12px',
      lineHeight: '20px',
    },
  },
  text_M_13to16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '13px',
      lineHeight: '22px',
    },
  },
  text_SB_14to18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_M_14to18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_M_14to20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  text_R_14to18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '26px',
    '@media (max-width: 1200px)': {
      fontSize: '14px',
      lineHeight: '24px',
    },
  },
  button_text: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '16px',
      lineHeight: '26px',
    },
  },
  landing_title: {
    fontFamily: 'pretendard',
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '50px',
    '@media (max-width: 1200px)': {
      fontSize: '24px',
      lineHeight: '34px',
    },
  },
  text_B_32: {
    fontFamily: 'pretendard',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '42px',
  },
  text_SB_32: {
    fontFamily: 'pretendard',
    fontSize: '32px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '42px',
  },
  text_B_24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '32px',
  },
  text_SB_24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
  },
  text_M_24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '32px',
  },
  text_R_24: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
  },
  text_B_20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '32px',
  },
  text_SB_20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
  },
  text_M_20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '32px',
  },
  text_R_20: {
    fontFamily: 'pretendard',
    fontSize: '20px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
  },
  text_B_18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '26px',
  },
  text_SB_18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '26px',
  },
  text_M_18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
  },
  text_R_18: {
    fontFamily: 'pretendard',
    fontSize: '18px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '26px',
  },
  text_B_16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '26px',
  },
  text_SB_16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '26px',
  },
  text_M_16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
  },
  text_R_16: {
    fontFamily: 'pretendard',
    fontSize: '16px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '26px',
  },
  text_B_14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '24px',
  },
  text_SB_14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '24px',
  },
  text_M_14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
  },
  text_R_14: {
    fontFamily: 'pretendard',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
  },
  text_SB_13: {
    fontFamily: 'pretendard',
    fontSize: '13px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '22px',
  },
  text_M_13: {
    fontFamily: 'pretendard',
    fontSize: '13px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '22px',
  },
  text_SB_12: {
    fontFamily: 'pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '20px',
  },
  text_M_12: {
    fontFamily: 'pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '18px',
  },
  text_R_12: {
    fontFamily: 'pretendard',
    fontSize: '12px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '18px',
  },
  header_title: {
    fontFamily: 'pretendard',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    '@media (max-width: 1200px)': {
      fontSize: '18px',
      lineHeight: '26px',
    },
  },
};
